### ISSUE TITLE
Missing database library

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/gemini#25]
Building a new Gemini project from the archetype, `com.techempower.data.jdbc` is unable to be resolved because the generated `pom.xml` does not have a dependency defined for it.

Adding the following resolves the issue:
```
        <dependency>
            <groupId>com.techempower</groupId>
            <artifactId>gemini-jdbc</artifactId>
            <version>2.22.0</version>
        </dependency>
```

**Comment by k-r-g** [comment]
I think I'm misunderstanding. I see this dependency in two places in the archetype:

https://github.com/TechEmpower/gemini/blob/master/gemini-resin-archetype/src/main/resources/archetype-resources/pom.xml#L33

https://github.com/TechEmpower/gemini/blob/master/gemini-resin-archetype/pom.xml#L61

**Comment by msmith-techempower** [comment]
I think this is related to my issue yesterday, which boiled down to "I should release 2.23.0 if I want these things to work right."
