### ISSUE TITLE
Add support for a root handler

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/gemini#33]
Currently, Gemini will check for path segments by count, and only look for a non-default handler if the count is greater than zero.

DOD: 
- [ ] Implement another `add` method with only `PathHandler<C> rootHandler` as the argument
- [ ] Implement `else if` check to `PathDispatcher#dispatch` after the `if (segments.getCount() > 0)` check to see if a root handler has been added and set that to the handler if so

**Comment by eluna-te** [comment]
https://github.com/TechEmpower/gemini/pull/37

**Comment by bhauer** [comment]
Let's discuss this. I'm not sure I understand the intended and actual difference from the existing default handler.  Reviewing the code, the actual difference isn't clear to me.

**Comment by msmith-techempower** [comment]
Specifically, we should be able to handle `/` outside of the default handler. Out of box, the default handler is a 404 handler, and that functionality should still work while providing a mechanism to serve something non-default from `/`

**Comment by msmith-techempower** [comment]
Resolved with #37
